openapi: 3.2.0
info:
  title: Mock Person Identifiers API
  version: 1.0.0
  contact:
    name: DoIT Enterprise Integration API Team
    email: api@doit.wisc.edu
    url: https://go.wisc.edu/k701y6
  description: A mock implementation of the Person API.
servers:
- url: https://mock.api.wisc.edu
security:
- OAuth2ClientCredentials: []
tags:
- name: Identifiers
paths:
  /people/{id}/identifiers:
    get:
      description: 'Get identifiers for a person. This endpoint returns all current and past identifiers for the person. These may be:


        pvi - Publicly Visible Identifier, a unique value from DoIT Identity and Access Management. Current and non-current PVIs are available.


        netId - Username for the NetID Login Service.


        emplId - Current emplIds from the Student Information System (SIS) for students, and non-current emplIds from the Human Resources System (HRS) for employees.


        libraryPatronId - As documented in this KB article.


        campusId - From Student Information System (SIS).


        predictedPhotoId - As documented in this KB article.


        eppn - As documented in this KB article.


        workerId - Identifier for a person from Workday. Also known as Employee ID.


        personNumber - Identifier for a person from UW Medical Foundation.


        manifestId - Identifier for a person in Manifest, UW''s tool for managing group access to campus resources. The source is IAM.


        wiscardId - The number printed on the person''s Wiscard. The source is WISCARD.'
      summary: Get identifiers
      operationId: get_person_identifiers
      tags:
      - Identifiers
      parameters:
      - name: id
        description: 'ID of a person. This parameter should not be manually built/concatenated, but instead be used by following the fully-formed links returned in an API response. To get a person by an ID, use query parameters to search by a specific identifier. Example: /people?filter[identifiers.name]=netId&filter[identifiers.value]=bbadger'
        in: path
        example: e2118c5a-aae2-4475-a661-bb0592effefa
        required: true
        schema:
          type: string
          description: An ephemeral identifier used only in the Person API to adhere to the [JSON:API specification](https://jsonapi.org/format/#document-resource-object-identification). This ID may change if a person is split into two people or two people are merged into one person. This ID is used for paginating results or following other links returned in the API response. This ID should not be stored in a consuming system. Concatenating parts of the URL to form a link is discouraged. Instead, use the fully-formed links returned in an API response.
      - name: fields
        in: query
        description: Specify the list of fields you would like to return for each resource type.  For example, `fields[people]=firstName,lastName` will just return the names for people.  If you are including related resources with 'includes' you can also specify fields on those resources as well.  For example, `includes=jobs&fields[people]=jobs&fields[jobs]=title` will just return titles for jobs.  See [Sparse Fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets) for more details.
        required: false
        style: deepObject
        explode: true
        schema:
          type: object
          additionalProperties: false
          properties:
            type:
              type: string
              example: people
      - name: advancedFilter
        in: query
        description: Filter results of query using the [Advanced Filter](https://kb.wisc.edu/uw-apis/158404#advanced-filters).
        required: false
        style: deepObject
        explode: true
        schema:
          type: object
          additionalProperties: false
          properties:
            attribute:
              type: string
              example: and(equals(firstName, "John"), equals(lastName, "Doe"))
      - name: filter[name]
        in: query
        required: false
        description: Filter results using the [filter query parameter family](https://jsonapi.org/recommendations/#filtering). Refer to the [Person API Documentation](https://kb.wisc.edu/uw-apis/158404) for more information. Filter `identifiers` resources by `name`.
        schema:
          type: string
          enum:
          - pvi
          - netId
          - emplId
          - libraryPatronId
          - campusId
          - predictedPhotoId
          - eppn
          - workerId
          - manifestId
      - name: filter[source]
        in: query
        required: false
        description: Filter results using the [filter query parameter family](https://jsonapi.org/recommendations/#filtering). Refer to the [Person API Documentation](https://kb.wisc.edu/uw-apis/158404) for more information. Filter `identifiers` resources by `source`.
        schema:
          type:
          - string
          - 'null'
      - name: filter[value]
        in: query
        required: false
        description: Filter results using the [filter query parameter family](https://jsonapi.org/recommendations/#filtering). Refer to the [Person API Documentation](https://kb.wisc.edu/uw-apis/158404) for more information. Filter `identifiers` resources by `value`.
        schema:
          type: string
      - name: filter[current]
        in: query
        required: false
        description: Filter results using the [filter query parameter family](https://jsonapi.org/recommendations/#filtering). Refer to the [Person API Documentation](https://kb.wisc.edu/uw-apis/158404) for more information. Filter `identifiers` resources by `current`.
        schema:
          type: boolean
      - name: filter[active]
        in: query
        required: false
        description: Filter results using the [filter query parameter family](https://jsonapi.org/recommendations/#filtering). Refer to the [Person API Documentation](https://kb.wisc.edu/uw-apis/158404) for more information. Filter `identifiers` resources by `active`.
        schema:
          type: boolean
      - name: filter[institution]
        in: query
        required: false
        description: Filter results using the [filter query parameter family](https://jsonapi.org/recommendations/#filtering). Refer to the [Person API Documentation](https://kb.wisc.edu/uw-apis/158404) for more information. Filter `identifiers` resources by `institution`.
        schema:
          type:
          - string
          - 'null'
      responses:
        '200':
          description: A collection of identifiers.
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                - data
                - links
                properties:
                  data:
                    description: A collection of identifiers
                    type: array
                    items:
                      description: Details about an identifier associated with a person.
                      type: object
                      required:
                      - type
                      - id
                      - attributes
                      - relationships
                      properties:
                        type:
                          type: string
                          example: identifiers
                        id:
                          type: string
                          description: Ephemeral ID used to adhere to the JSON:API specification. This ID should not be stored.
                        attributes:
                          type: object
                          required:
                          - name
                          - source
                          - value
                          - current
                          - institution
                          properties:
                            name:
                              type: string
                              example: pvi
                              enum:
                              - pvi
                              - netId
                              - emplId
                              - libraryPatronId
                              - campusId
                              - predictedPhotoId
                              - eppn
                              - workerId
                              - wiscardId
                              - manifestId
                              description: The name of this identifier.
                            source:
                              description: The source of an identifier resource.
                              type: string
                              enum:
                              - IAM
                              - HRS
                              - SIS
                              - LIBRARY
                              - WISCARD
                              - Workday
                              example: IAM
                            value:
                              type: string
                              example: UW123A456
                              minLength: 1
                            current:
                              description: Property that indicates if this identifier is currently used. The identifiers 'pvi' and 'emplId' are available as current and non-current. All other identifiers are only available in their current versions.
                              type: boolean
                              example: true
                            active:
                              description: If false, no further changes are being made to the identifier. This field is only visible if the requesting application has access to the Inactive Population.
                              type: boolean
                              example: true
                            institution:
                              description: The institution associated with the resource.
                              type: string
                              example: UW-Madison
                              enum:
                              - Shared
                              - UW-Eau Claire
                              - UW-Green Bay
                              - UW-La Crosse
                              - UW-Madison
                              - UW-Milwaukee
                              - UW Oshkosh
                              - UW-Parkside
                              - UW-Platteville
                              - UW-River Falls
                              - UW-Stevens Point
                              - UW-Stout
                              - UW-Superior
                              - UW-Whitewater
                              - UW-Extension
                              - UW System
                        relationships:
                          type: object
                          properties:
                            person:
                              description: A generic relationship object
                              type: object
                              properties:
                                links:
                                  type: object
                                  properties:
                                    related:
                                      type: string
                                      example: https://api.wisc.edu/link/to/related/object
                                data:
                                  type:
                                  - object
                                  - 'null'
                                  properties:
                                    type:
                                      type: string
                                      example: sampleType
                                    id:
                                      type: string
                                      example: sampleId
                  links:
                    description: The link to access a resource itself
                    type: object
                    properties:
                      self:
                        type: string
                        example: https://api.wisc.edu/link/to/self
              examples:
                example-identifiers-current:
                  value:
                    data:
                    - attributes:
                        name: pvi
                        source: IAM
                        value: UW123A456
                        current: true
                        institution: Shared
                        active: true
                      id: 49dcd8cc-0778-4826-9304-d99b57266005
                      relationships:
                        person:
                          data:
                            id: e2118c5a-aae2-4475-a661-bb0592effefa
                            type: people
                          links:
                            related: https://api.wisc.edu/people/e2118c5a-aae2-4475-a661-bb0592effefa
                      type: identifiers
                    links:
                      self: https://api.wisc.edu/people/e2118c5a-aae2-4475-a661-bb0592effefa/identifiers
                example-identifier-historical:
                  value:
                    data:
                    - attributes:
                        name: pvi
                        source: IAM
                        value: UW123A123
                        current: false
                        institution: Shared
                        active: true
                      id: 9cd5e701-114e-42d3-bba6-886ada90b196
                      relationships:
                        person:
                          data:
                            id: e2118c5a-aae2-4475-a661-bb0592effefa
                            type: people
                          links:
                            related: https://api.wisc.edu/people/e2118c5a-aae2-4475-a661-bb0592effefa
                      type: identifiers
                    links:
                      self: https://api.wisc.edu/people/e2118c5a-aae2-4475-a661-bb0592effefa/identifiers
        '400':
          description: A bad request.
          content:
            application/vnd.api+json:
              schema:
                description: A JSON:API error response body containing one or more errors.
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      description: An error
                      type: object
                      properties:
                        id:
                          type:
                          - string
                          - 'null'
                          example: 0fd247d9-a93c-4b48-bde8-247ce352ebcb
                        status:
                          type: integer
                          example: 400
                        title:
                          type: string
                          example: Error title
                        detail:
                          type: string
                          example: Additional details about the error
                        links:
                          type: object
                        meta:
                          type: object
                        source:
                          type: object
              examples:
                application/vnd.api+json:
                  value:
                    errors:
                    - id: 0fd247d9-a93c-4b48-bde8-247ce352ebcb
                      links: {}
                      meta: {}
                      source: {}
                      status: 400
                      title: Bad Request
                      detail: Invalid properties in query parameters - resource type 'people' has no attribute 'invalid'.
        '401':
          description: Incorrect or expired OAuth token.
          content:
            application/vnd.api+json:
              schema:
                description: A JSON:API error response body containing one or more errors.
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      description: An error
                      type: object
                      properties:
                        id:
                          type:
                          - string
                          - 'null'
                          example: 0fd247d9-a93c-4b48-bde8-247ce352ebcb
                        status:
                          type: integer
                          example: 400
                        title:
                          type: string
                          example: Error title
                        detail:
                          type: string
                          example: Additional details about the error
                        links:
                          type: object
                        meta:
                          type: object
                        source:
                          type: object
              examples:
                unauthorized-response:
                  value:
                    errors:
                    - status: 401
                      title: Unauthorized
                      detail: Invalid OAuth authentication - InvalidAccessToken
        '403':
          description: The API call is authenticated but the client isn't allowed to perform the requested operation. This can occur when trying to update a resource when granted read-only access.
          content:
            application/vnd.api+json:
              schema:
                description: A JSON:API error response body containing one or more errors.
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      description: An error
                      type: object
                      properties:
                        id:
                          type:
                          - string
                          - 'null'
                          example: 0fd247d9-a93c-4b48-bde8-247ce352ebcb
                        status:
                          type: integer
                          example: 400
                        title:
                          type: string
                          example: Error title
                        detail:
                          type: string
                          example: Additional details about the error
                        links:
                          type: object
                        meta:
                          type: object
                        source:
                          type: object
              examples:
                name-update-example:
                  value:
                    errors:
                    - status: 403
                      title: Forbidden
                      detail: Client is not allowed to create, update, or delete a person's name.
                no-access-example:
                  value:
                    errors:
                    - status: 403
                      title: Forbidden
                      detail: Requested method is forbidden for endpoint - GET - /people
                disabled-temporarily-example:
                  value:
                    errors:
                    - status: 403
                      title: Forbidden
                      detail: Webhook Create/Update/Delete operations are disabled temporarily. Try again later.
        '404':
          description: Unable to find the specified record
          content:
            application/vnd.api+json:
              schema:
                description: A JSON:API error response body containing one or more errors.
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      description: An error
                      type: object
                      properties:
                        id:
                          type:
                          - string
                          - 'null'
                          example: 0fd247d9-a93c-4b48-bde8-247ce352ebcb
                        status:
                          type: integer
                          example: 400
                        title:
                          type: string
                          example: Error title
                        detail:
                          type: string
                          example: Additional details about the error
                        links:
                          type: object
                        meta:
                          type: object
                        source:
                          type: object
              examples:
                not-found-example:
                  value:
                    errors:
                    - status: 404
                      title: Not Found
                      detail: Requested resource not found.
        '406':
          description: Servers respond with a 406 Not Acceptable status code if a request’s Accept header contains the JSON:API media type and all instances of that media type are modified with media type parameters.
          content:
            application/vnd.api+json:
              schema:
                description: A JSON:API error response body containing one or more errors.
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      description: An error
                      type: object
                      properties:
                        id:
                          type:
                          - string
                          - 'null'
                          example: 0fd247d9-a93c-4b48-bde8-247ce352ebcb
                        status:
                          type: integer
                          example: 400
                        title:
                          type: string
                          example: Error title
                        detail:
                          type: string
                          example: Additional details about the error
                        links:
                          type: object
                        meta:
                          type: object
                        source:
                          type: object
              examples:
                not-acceptable-example:
                  value:
                    errors:
                    - status: 406
                      title: Not Acceptable
                      detail: Request's Accept header contained the JSON:API media type and all instances of that media type were modified with media type parameters.
        '429':
          description: The API quota has been exceeded.
          content:
            application/vnd.api+json:
              schema:
                description: A JSON:API error response body containing one or more errors.
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      description: An error
                      type: object
                      properties:
                        id:
                          type:
                          - string
                          - 'null'
                          example: 0fd247d9-a93c-4b48-bde8-247ce352ebcb
                        status:
                          type: integer
                          example: 400
                        title:
                          type: string
                          example: Error title
                        detail:
                          type: string
                          example: Additional details about the error
                        links:
                          type: object
                        meta:
                          type: object
                        source:
                          type: object
              examples:
                not-found-example:
                  value:
                    errors:
                    - status: 429
                      title: Too Many Requests
                      detail: The quota has been exceeded.
        '500':
          description: An unexpected error.
          content:
            application/vnd.api+json:
              schema:
                description: A JSON:API error response body containing one or more errors.
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      description: An error
                      type: object
                      properties:
                        id:
                          type:
                          - string
                          - 'null'
                          example: 0fd247d9-a93c-4b48-bde8-247ce352ebcb
                        status:
                          type: integer
                          example: 400
                        title:
                          type: string
                          example: Error title
                        detail:
                          type: string
                          example: Additional details about the error
                        links:
                          type: object
                        meta:
                          type: object
                        source:
                          type: object
              examples:
                not-found-example:
                  value:
                    errors:
                    - status: 500
                      title: Internal Server Error
                      detail: Something went wrong in the server-side.
components:
  securitySchemes:
    OAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.wisc.edu/oauth/token
          scopes: {}
externalDocs:
  description: Read more about JSON:API here
  url: https://jsonapi.org/
